$('#index-org .slider__slide').equalHeights();
$('#index-study .slider__slide').equalHeights();
$('#index-success .slider__slide').equalHeights();
$('#about-space .slider__slide').equalHeights();
$('#about-academy .slider__slide').equalHeights();
$('#about-history .slider__slide').equalHeights();
$('#about-success .slider__slide').equalHeights();
$('#about-community .slider__slide').equalHeights();
$('#corps-sponsor .slider__slide').equalHeights();
